Dadata demo
CX-Box/cxbox-demo pull request #3
Opened 2023-06-07 15:34 UTC by myangrysoul

2023-07-05 12:46 UTC, IgorNB commented
Front:
1.1) не даёт вбить свое значение. Даже если я напечатал то чего в подсказках нет и кликнул мимо или ещё как-то вышел из редактирования, то должно остаться то что напечатано
1.2) когда начинаю редактировать - текущее значение стирается (надо чтоб оставалось и я его дописывал)
1.3) если в поле типа suggestion ставлю значение на бэке (при изменении другого поля). То фронт изменённое значение с бэка не отображает 
1.4) если в поле типа suggestion ставлю значение через pickmap вызванный на другом поле, то изменения снова не видны
1.5) почемуто в пикмапе ждет только value имя поля справа — а должен брать из пикмапы а не хардкодом!
1.6) когда поле начал вбивать и бросил оно обводится красным и что-то пишет свое (не зависимо от того поле required или нет) — это поведение надо убрать и оставить только required стандантное поведение
1.7) когда поле выбрал оно обводится в зеленую рамку - тоже надо убрать

Back:
2.1) Филд экстракторы как то усложнены - непонятно зачем
2.2) почему-то не использован стартер дадаты на бэке, а сделана своя интеграция -- почему? Он сильно сокращает трудозатраты вроде

2023-07-05 12:47 UTC, IgorNB commented
Front:
1.1) не даёт вбить свое значение. Даже если я напечатал то чего в подсказках нет и кликнул мимо или ещё как-то вышел из редактирования, то должно остаться то что напечатано
1.2) когда начинаю редактировать - текущее значение стирается (надо чтоб оставалось и я его дописывал)
1.3) если в поле типа suggestion ставлю значение на бэке (при изменении другого поля). То фронт изменённое значение с бэка не отображает
1.4) если в поле типа suggestion ставлю значение через pickmap вызванный на другом поле, то изменения снова не видны
1.5) почемуто в пикмапе ждет только value имя поля справа — а должен брать из пикмапы а не хардкодом!
1.6) когда поле начал вбивать и бросил оно обводится красным и что-то пишет свое (не зависимо от того поле required или нет) — это поведение надо убрать и оставить только required стандантное поведение
1.7) когда поле выбрал оно обводится в зеленую рамку - тоже надо убрать

Back:
2.1) Филд экстракторы как то усложнены - непонятно зачем
2.2) почему-то не использован стартер дадаты на бэке, а сделана своя интеграция -- почему? Он сильно сокращает трудозатраты вроде

2023-07-05 12:48 UTC, IgorNB requested changes
Front:
1.1) не даёт вбить свое значение. Даже если я напечатал то чего в подсказках нет и кликнул мимо или ещё как-то вышел из редактирования, то должно остаться то что напечатано
1.2) когда начинаю редактировать - текущее значение стирается (надо чтоб оставалось и я его дописывал)
1.3) если в поле типа suggestion ставлю значение на бэке (при изменении другого поля). То фронт изменённое значение с бэка не отображает
1.4) если в поле типа suggestion ставлю значение через pickmap вызванный на другом поле, то изменения снова не видны
1.5) почемуто в пикмапе ждет только value имя поля справа — а должен брать из пикмапы а не хардкодом!
1.6) когда поле начал вбивать и бросил оно обводится красным и что-то пишет свое (не зависимо от того поле required или нет) — это поведение надо убрать и оставить только required стандантное поведение
1.7) когда поле выбрал оно обводится в зеленую рамку - тоже надо убрать

Back:
2.1) Филд экстракторы как то усложнены - непонятно зачем
2.2) почему-то не использован стартер дадаты на бэке, а сделана своя интеграция -- почему? Он сильно сокращает трудозатраты вроде

2023-10-20 14:32 UTC, Lourence94 approved these changes

2024-02-15 10:52 UTC, merged